
theme: anatole
languageCode: "ar-SA"
defaultContentLanguage: ar
baseURL: "https://xn----ymcbabvy2f0eac0ah2c.xn--mgberp4a5d4ar"
logopath: images/aat-logo.svg
enableEmoji: true

languages:
  ar:
    # baseURL: "https://xn----ymcbabvy2f0eac0ah2c.xn--mgberp4a5d4ar"
    params:
    languageName: عربي
    languagedirection: "rtl"
    languageCode: ar-SA
    title: فضاء عبدالله
    Author: عبدالله الثاني
    description: "عالم من خيالي"
    weight: 1
    #links
    permalinks:
      post: /مقالات/:title/
      about: /:title
      # authors: /الكاتب/:title/
  en:
    # baseURL: "https://abdullahalthani.com"
    params:
    languageName: English
    languageCode: en
    title: Abdullah's space
    Author: Abdullah AlThani
    description: "A world of my imagination"
    weight: 2
    permalinks:
      post: /posts/:title/
      # authors: /author/:title/
    languagedirection: "ltr"

pygmentsstyle: 'monokai'
disqusShortname: abdla
googleAnalytics: UA-166633314-1


# # Theme settings
# theme: hugo-theme-novela
# paginate: 6
# social:
#   twitter: "https://twitter.com/AAThani"
#   github: "http://github.com/l3b"
# # instagram: "#"
#   linkedin: "https://https://www.linkedin.com/in/abdullah-al-thani/"
#   dribbble: "#"
#  # youtube: "#"
# taxonomies:
#   author: authors

# paginate: 10
# paginatePath: "page"
# rssLimit: 20
# author:
#   name: "Abdullah AlThani"
#   url: "/about"
#   avatar: "/content/images/hiking profile-small.jpg"

# outputFormats:
#   SearchIndex:
#     mediaType: "application/json"
#     baseName: "searchindex"
#     isPlainText: true
#     notAlternative: true

# outputs:
#   home: ["HTML","RSS", "JSON", "SearchIndex"]
#   section: ["HTML","RSS", "JSON"]

params:
  contact: "hello@thani.me"
  logo: false
  # copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: true
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  mobileMenu: true
  poweredby: false
  sidebar: false
  submitted: true
  Subtitle: test
  profilePicture: "/images/aat-logo.svg"
  # mainSections:             # The sections you want to have listed on the front page.
  #   - "section1"            # Default to the section with most content if not set.
  #   - "section2"            # Set to empty if no section should be listed.
  #   - "about"
