baseURL: "https://example.com"
languageCode: "ar-sa"
title: "فضاء عبدالله"
pygmentsstyle: 'monokai'
disqusShortname: abdla

# Theme settings
theme: hugo-theme-novela
paginate: 6
social:
  twitter: "http://abd.la/tw"
# github: "#"
# instagram: "#"
# linkedin: "abd.la/in"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
